version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: heyv-db
    ports:
      - 3306:3306
    depends_on:
      - adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  api:
    build: server/
    environment:
      NODE_ENV: development
      PORT: 8000
      CORS_ORIGIN: http://localhost
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password1
      DB_DATABASE: heyv-db
    ports:
      - 8000:8000
    depends_on:
      - db
  
  client:
    build: client/
    ports:
      - 80:80