[project]
name = "heyv"
version = "0.1.0"
requires-python = ">=3.13,<3.14"

dependencies = [
  "Django>=6.0,<7.0",
  "django-cors-headers>=4.7",
  "django-filter>=25.2",
  "djangorestframework>=3.17",
  "djangorestframework-simplejwt>=5.5",
]

[dependency-groups]
dev = [
  "ruff>=0.15.12",
  "basedpyright>=1.39.9",
  "django-stubs>=6.0.7",
  "djangorestframework-stubs>=3.17.1",
]

production = [
  "gunicorn>=24.0,<25.0",
  "psycopg[binary]>=3.2,<4.0",
  "whitenoise>=6.9,<7.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]

ignore = [
  "E501", # Never enforce `E501` (line length violations), which can be trivial.
  "D100", # Never warn about missing public docstrings.
  "D101", # Ignore missing docstring public class.
  "D102", # Ignore missing docstring public method.
  "D105", # Ignore docstrings in magic methods.
  "D106", # Ignore docstrings in nested methods.
  "D202", # Ignore blank line after dosctrings.
  "D212", # Ignore first line docstrings.
]
select = [
  "C",   # Convention violations, like coding standards issues (PEP8)
  "E",   # Errors that could cause exceptions or major functionality issues
  "F",   # Flaws in type annotations
  "I",   # Import-related linting issues
  "W",   # Warnings for stylistic or minor programming issues
  "PL",  # PyLint checks, including unused function variables
  "N",   # Naming convention checks (PEP8)
  "D",   # Docstring style checks, often based on Google's style guidelines
  "UP",  # Checks for deprecated Python features that could be upgraded
  "FIX", # Reminder tags for TODOs and FIXMEs in the code
]
pydocstyle.convention = "google"


# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104", "E402", "F401", "F403", "F811"]
"**/migrations/*" = ["D"]
"manage.py" = ["PLC0415"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.django-stubs]
django_settings_module = "heyv.settings.local"

[tool.djangorestframework-stubs]
django_settings_module = "heyv.settings.local"
