# Generated by Django 6.0.5 on 2026-05-10 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='last_done_date',
            field=models.DateField(blank=True, help_text='Last date when the task has been done. It is the starting point for the internal. If not present, it will take the creation date.', null=True),
        ),
    ]
