# Generated by Django 6.1 on 2026-08-13 21:23

import app.models.recurrence_rule
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='interval',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='week_position',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, validators=[app.models.recurrence_rule.validate_weekdays]),
        ),
        migrations.AlterField(
            model_name='taskoccurrence',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='app.tasktemplate'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='title',
            field=models.CharField(help_text='Title of the task.', max_length=255),
        ),
    ]
