# Generated by Django 6.0.5 on 2026-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_due_date_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date of the task. Re-calculated when the last_done_date is updated.', null=True),
        ),
    ]
