# Generated by Django 6.1 on 2026-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tasktemplate_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'TODO')), fields=('task_template',), name='unique_todo_occurrence_per_template'),
        ),
    ]
