# Generated by Django 6.0.5 on 2026-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Required. Name of the category.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(help_text='Required. Interval of the task. Format : d w m y.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Required. Name of the task.', max_length=255),
        ),
    ]
