# Generated by Django 6.0.5 on 2026-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_updated_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(default='1 0 0 0', help_text='Required. Interval of the task. Format : d w m y.', max_length=255),
        ),
    ]
