# Generated by Django 6.0.5 on 2026-07-07 10:50

from django.db import migrations, models

import app.models.task


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_category_options_alter_task_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.AlterField(
            model_name="task",
            name="interval",
            field=models.CharField(
                default="1 0 0 0",
                help_text="Required. Interval of the task. Format: d w m y.",
                max_length=255,
                validators=[app.models.task.validate_interval],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_done_date",
            field=models.DateField(
                blank=True,
                help_text="Last date when the task has been done. It is the starting point for the interval. If not present, it will take the creation date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(to="app.category"),
        ),
    ]
